### PR TITLE
fix(tree): toast feedback when copying tree-row path (#18)

### LINKED ISSUE #18: copyPath in tree gives no confirmation feedback
When a user clicks the copy-path chain-link button on a tree row, `navigator.clipboard.writeText` is called inside a try/catch that silently swallows errors. There is no toast, snackbar, icon-state change, or other affordance to confirm the copy succeeded (or that it failed, e.g., when the page is not focused or clipboard permission is denied).

**Expected:** Brief visual confirmation (Material snackbar "Path copied" or a 1s icon check swap).

**Source:** `src/app/shared/components/json-tree/json-tree.component.ts` `copyPath()`.

**Spec reference:** DESIGN_SPEC.md — feedback on user actions.

### PR DESCRIPTION
**Pull request by geevensingh**
Closes #18.

## Problem

Clicking the chain-link copy-path button on a tree row called `navigator.clipboard.writeText` inside a `try / catch { /* ignore */ }`. The user got no confirmation that the copy succeeded, and silent swallowing of the failure path (unfocused page, denied clipboard permission, no API at all on older browsers) meant a user could think they had copied a path when they actually hadn't.

## Change

`copyPath()` now mirrors the existing `home.component.ts onCopyShareLink` pattern using `MatSnackBar`:

| Outcome | Snackbar | Duration |
|---|---|---|
| Success | `Path copied to clipboard.` | 2 s |
| Failure (rejected) | `Failed to copy path.` | 4 s |
| Unsupported (no `navigator.clipboard`) | `Copy is not supported in this browser.` | 4 s |

All three messages use a `Dismiss` action (reusing the existing `@@common.dismiss` i18n string).

## Files

- `src/app/shared/components/json-tree/json-tree.component.ts` -- inject `MatSnackBar`; rewrite `copyPath()`.
- `src/app/shared/components/json-tree/json-tree.component.spec.ts` -- provide a stubbed `MatSnackBar` in `createWith()`; add three new tests under a `copyPath` describe (success / failure / unsupported).
- `src/locale/messages.xlf` -- regenerated via `npm run extract-i18n` (3 new strings: `@@tree.copyPath.success` / `.failed` / `.unsupported`).

## Validation

- `npm run lint` (incl. `check:ascii` / `check-spec-patterns`) -- PASS
- `npm run test:ci` -- 608 of 610 PASS, 2 skipped
- `npm run build` -- PASS

### CODE REVIEW

File: src/app/shared/components/json-tree/json-tree.component.ts [hunk 1]
```diff
@@ -693,11 +695,32 @@ export class JsonTreeComponent {
   }
 
   copyPath(node: TreeNode): void {
```
Comment (geevensingh) [inline src/app/shared/components/json-tree/json-tree.component.ts:697]: Follow-up suggestion (not blocking this PR): `onCopyShareLink` in `home.component.ts` and this method are now nine-line copy-paste twins of each other, modulo three i18n IDs and a duration. A small helper would DRY this up and pay off the next time someone adds a "copy X" button:

```ts
clipboardService.copyWithToast(text, {
  successId, failedId, unsupportedId, successDurationMs?
});
```

Worth filing a separate issue rather than expanding scope here.

File: src/app/shared/components/json-tree/json-tree.component.spec.ts [hunk 2]
```diff
@@ -18,13 +19,18 @@ describe('JsonTreeComponent', () => {
...
   async function createWith(value: unknown): Promise<void> {
     localStorage.removeItem(STORAGE_KEY);
     TestBed.resetTestingModule();
+    snackOpen = jasmine.createSpy('snackOpen');
     await TestBed.configureTestingModule({
       imports: [JsonTreeComponent],
-      providers: [...provideFakeAuth()]
+      providers: [
+        ...provideFakeAuth(),
+        { provide: MatSnackBar, useValue: { open: snackOpen } }
```
Comment (geevensingh) [inline src/app/shared/components/json-tree/json-tree.component.spec.ts]: nit: this provider is now installed for *every* test in this file, but only the three `copyPath` cases use it. Scoping it to a `beforeEach` inside `describe('copyPath', ...)` keeps the rest of the suite honest about what they depend on. Not blocking.

File: src/app/shared/components/json-tree/json-tree.component.spec.ts [hunk 3]
```diff
@@ -656,6 +662,69 @@ describe('JsonTreeComponent', () => {
...
+          });
+        }
+      }
+    }
+
+    it('opens a success snackbar after writeText resolves', async () => {
+      await createWith({ a: 1 });
+      const writeText = jasmine.createSpy('writeText').and.resolveTo(undefined);
+      await withClipboard({ writeText }, async () => {
+        cmp.copyPath({ pathString: '$.a' } as never);
```
Comment (geevensingh) [inline src/app/shared/components/json-tree/json-tree.component.spec.ts]: nit: `as never` skips the type system entirely (and applies to all three new cases). Prefer `as unknown as TreeNode`, or a tiny fixture helper like:

```ts
const nodeFixture = (path: string) => ({ pathString: path }) as unknown as TreeNode;
```

If `copyPath` ever starts touching another field on `node`, the current cast will silently keep compiling while the test stops representing reality.

File: src/app/shared/components/json-tree/json-tree.component.spec.ts [hunk 4]
```diff
@@ -656,6 +662,69 @@ describe('JsonTreeComponent', () => {
...
+        await Promise.resolve();
+        await Promise.resolve();
```
Comment (geevensingh) [inline src/app/shared/components/json-tree/json-tree.component.spec.ts]: nit: two manual microtask flushes is fragile — if the `.then` chain ever grows another link (or someone adds an `await` inside the success/failure handler), tests will silently start asserting before the snackbar opens. `await fixture.whenStable()` is more robust to that, and `fakeAsync` + `tick()` is the strictest option. Same applies in the failure-case test below.

File: src/app/shared/components/json-tree/json-tree.component.ts [hunk 5]
```diff
@@ -693,11 +695,32 @@ export class JsonTreeComponent {
   }
 
   copyPath(node: TreeNode): void {
-    try {
-      void navigator.clipboard?.writeText(node.pathString);
-    } catch {
-      /* ignore */
+    const dismiss = $localize`:@@common.dismiss:Dismiss`;
+    const clipboard = navigator.clipboard;
+    if (!clipboard?.writeText) {
```
Comment (geevensingh) [inline src/app/shared/components/json-tree/json-tree.component.ts:701]: minor: a one-line comment here would help the next reader — `!clipboard?.writeText` covers (a) older browsers with no Clipboard API at all and (b) modern browsers where the page is served over an insecure context (HTTP, file://) so `navigator.clipboard` is `undefined`. Easy to mistake this for redundant null-checking otherwise.

File: src/app/shared/components/json-tree/json-tree.component.ts [hunk 6]
```diff
@@ -693,11 +695,32 @@ export class JsonTreeComponent {
...
+        { duration: 4000 }
+      );
+      return;
     }
+    clipboard.writeText(node.pathString).then(
+      () => {
+        this.snack.open(
+          $localize`:@@tree.copyPath.success:Path copied to clipboard.`,
+          dismiss,
+          { duration: 2000 }
```
Comment (geevensingh) [inline src/app/shared/components/json-tree/json-tree.component.ts]: Inconsistency with `home.component.ts onCopyShareLink`, which uses `duration: 3000` for the success toast (failure is 4000 in both). Worth aligning to a single number across the app — I don't have a strong opinion on which, but a UX constant in shared/utils would prevent this drifting further.

**Review by geevensingh — COMMENTED** [review]
Approach is right — this is a faithful clone of the established `onCopyShareLink` pattern in `home.component.ts`, including the i18n IDs, the `.then(success, fail)` shape, and the `@@common.dismiss` action. None of my comments below are blockers; they're nits + one suggested follow-up issue (the helper-extraction comment).

File: src/app/shared/components/json-tree/json-tree.component.ts (hunk 1 above)
Comment (geevensingh) [reply src/app/shared/components/json-tree/json-tree.component.ts:697]: @copilot , please create an issue for this.  We'll fix separately, but not in this PR.  When you've created the issue, please close this comment.

File: src/app/shared/components/json-tree/json-tree.component.spec.ts (hunk 2 above)
Comment (geevensingh) [reply src/app/shared/components/json-tree/json-tree.component.spec.ts]: Nah, this doesn't seem important.

File: src/app/shared/components/json-tree/json-tree.component.spec.ts (hunk 3 above)
Comment (geevensingh) [reply src/app/shared/components/json-tree/json-tree.component.spec.ts]: @copilot What is the difference between "as never" and "as unknown as TreeNode"?
Could  we just do "as TreeNode" instead?  Why not?
